# Import pandas

In [1]:
import pandas as pd
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.reset_option('display.max_rows')
#pd.reset_option('display.max_columns')

# Load in the dataframes

In [3]:
df = pd.read_csv("data/laborSummaryData.csv") 
df = df[df["annual_average_employees"] > 0]
df["All Types of Injuries"] = df["total_injuries"] + df["total_skin_disorders"] + df["total_respiratory_conditions"] + df["total_poisonings"] + df["total_hearing_loss"] + df["total_other_illnesses"]
df

/var/folders/wc/_9yyz6mj6m94jttqx0d2fw540000gn/T/ipykernel_53550/4089018912.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/laborSummaryData.csv")

,id,establishment_name,establishment_id,ein,company_name,street_address,city,state,zip_code,naics_code,naics_year,industry_description,establishment_type,size,annual_average_employees,total_hours_worked,no_injuries_illnesses,total_deaths,total_dafw_cases,total_djtr_cases,total_other_cases,total_dafw_days,total_djtr_days,total_injuries,total_skin_disorders,total_respiratory_conditions,total_poisonings,total_hearing_loss,total_other_illnesses,created_timestamp,change_reason,year_filing_for,sector,zipcode,naics_char,All Types of Injuries
0,2808362,AristaCare at Meadow Springs,41940,204755042.0,AristaCare at Meadow Springs LLC,845 Germantown Pike,Plymouth Meeting,PA,19462,623110,2012,Skilled nursing facilities,1.0,3,315,389754,1,0,1,5,1,1,32,7,0,0,0,0,0,28FEB25:16:35:00,NaN,2024,Health Care and Social Assistance,19462,623110,7
1,2587120,AM Braswell Jr. Food Company,41942,580667528.0,AM Braswell Jr. Food Company,226 North Zetterower Avenue,Statesboro,GA,30458,311421,2012,Canning jams and jellies,1.0,22,119,98259,1,0,7,4,0,46,69,10,0,0,0,0,1,31JAN25:20:24:00,NaN,2024,Manufacturing,30458,311421,11
2,2575264,"SMM Group Chesapeake, VA",41952,453807558.0,Sims Metal Management,4300 Buell Street,Chesapeake,VA,23324,423930,2012,Metal scrap and waste merchant wholesalers,1.0,22,126,278678,1,0,0,0,1,0,0,1,0,0,0,0,0,29JAN25:14:47:00,NaN,2024,Wholesale Trade,23324,423930,1
3,2575218,"SMM Group Richmond, VA",41955,453807558.0,Sims Metal Management,3220 Deepwater Terminal Road,Richmond,VA,23234,423930,2012,Metal scrap and waste merchant wholesalers,1.0,21,35,68943,2,0,0,0,0,0,0,0,0,0,0,0,0,29JAN25:14:31:00,NaN,2024,Wholesale Trade,23234,423930,0
4,2505064,FRP Sheet Metal Contracting Corp,41983,112459740.0,FRP Sheet Metal Contracting Corp,365 Wyandanch Ave.,West Babylon,NY,11704,238220,2012,Air-conditioning system (except window) instal...,1.0,21,25,40919,2,0,0,0,0,0,0,0,0,0,0,0,0,07JAN25:20:06:00,NaN,2024,Construction,11704,238220,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390146,2887645,"Flinthills Trading Company, LLC DBA Huyett",1415414,481122201.0,"Flinthills Trading Company, LLC DBA Huyett",1215 E 8th St.,Minneapolis,KS,67467,332722,2022,"Nuts, metal, manufacturing",1.0,22,237,446911,1,0,0,1,2,0,10,3,0,0,0,0,0,30APR25:21:23:00,NaN,2024,Manufacturing,67467,332722,3
390147,2887648,COBICA INTERNATIONAL CORP,1415415,NaN,COBICA international Corp,"930 Carter Road, Suite 218.",Orlando,FL,34786,238160,2022,"Painting, spraying, or coating, roof",1.0,21,60,43881,2,0,0,0,0,0,0,0,0,0,0,0,0,30APR25:21:56:00,NaN,2024,Construction,34786,238160,0
390148,2887649,Brookdale Harbor Bay,1415416,601712839.0,Brookdale Senior Living,"9324 N. Harborview Drive, Gig Harbor",Gig Harbor,WA,98332,623312,2022,Assisted-living facilities without on-site nur...,1.0,21,25,4200598,2,0,0,0,0,0,0,0,0,0,0,0,0,30APR25:22:14:00,NaN,2024,Health Care and Social Assistance,98332,623312,0
390149,2887652,Unified Community Connections,1415417,520696384.0,Unified Community Connections,952 Ridgebrook Road,Sparks,MD,21152,623990,2022,Group homes for the disabled without nursing care,1.0,3,389,690924,1,0,18,0,26,193,155,43,0,0,0,0,1,30APR25:23:10:00,NaN,2024,Health Care and Social Assistance,21152,623990,44
390150,2887653,Allied Metal Company,1415418,100282704.0,Allied Metal Co,3440 Lightfoot Mill Rd,Chattanooga,TN,37406,331314,2022,"Aluminum ingot, secondary smelting of aluminum...",1.0,21,29,80910,1,0,1,1,0,5,89,2,0,0,0,0,0,30APR25:23:17:00,NaN,2024,Manufacturing,37406,331314,2

# Sort the dataframe by the companies with the largest amount of injuries reported

In [131]:
df.sort_values(by="All Types of Injuries", ascending=False)

,id,establishment_name,establishment_id,ein,company_name,street_address,city,state,zip_code,naics_code,naics_year,industry_description,establishment_type,size,annual_average_employees,total_hours_worked,no_injuries_illnesses,total_deaths,total_dafw_cases,total_djtr_cases,total_other_cases,total_dafw_days,total_djtr_days,total_injuries,total_skin_disorders,total_respiratory_conditions,total_poisonings,total_hearing_loss,total_other_illnesses,created_timestamp,change_reason,year_filing_for,sector,zipcode,naics_char,All Types of Injuries
24490,2665503,Walt Disney Parks and Resorts US Inc,225446,952412883.0,NaN,1375 Buena Vista Drive,Lake Buena Vista,FL,32830,713110,2012,NaN,1.0,3,68976,104795796,1,0,797,1947,310,6952,82606,2411,9,1,0,11,622,13FEB25:20:31:00,NaN,2024,"Arts, Entertainment, and Recreation",32830,713110,3054
173145,2556053,Chicago Public Schools,1102514,366005821,Chicago Public Schools,42 W. Madison,Chicago,IL,60602,611110,2022,"Academies, elementary or secondary",3.0,3,45000,46478779,1,1,342,5,2159,28641,7683,69,0,0,1,0,2437,24JAN25:16:46:00,NaN,2024,Educational Services,60602,611110,2507
97478,2720231,ABM INDUSTRIES INCORPORATED,858890,941369354.0,ABM,"14141 SOUTHWEST FRWY, SUITE 400",SUGAR LAND,TX,77478,531120,2012,"Building, nonresidential (except miniwarehouse...",1.0,3,79907,174222381,1,0,966,700,738,54436,40223,2375,2,20,1,0,6,24FEB25:15:31:00,NaN,2024,Real Estate and Rental and Leasing,77478,531120,2404
291755,2679236,"Walt Disney Parks and Resorts U.S. Inc., dba D...",1313632,952412883.0,The Walt Disney Company,1313 S. Harbor Blvd,Anaheim,CA,92802,713110,2022,"Amusement parks (e.g., theme, water)",1.0,3,40525,53684779,1,1,999,1116,250,47502,88529,1952,1,0,0,2,411,25FEB25:19:14:00,NaN,2024,"Arts, Entertainment, and Recreation",92802,713110,2366
105627,2666800,NA-US-CA-Fremont-45500 Fremont Blvd,899222,912197729.0,Tesla,45500 Fremont Blvd,Fremont,CA,94538,336110,2012,Automobile Manufacturing,1.0,3,18803,51578356,1,0,1113,304,544,47503,19008,1896,7,3,0,0,55,21FEB25:14:47:00,NaN,2024,Manufacturing,94538,336110,1961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241622,2523444,0507 Real Estate,1260043,421724313.0,BrightView,980 Jolly Road,Blue Bell,PA,19422,561730,2022,Landscaping Services,1.0,1,5,9594,2,0,0,0,0,0,0,0,0,0,0,0,0,15JAN25:18:37:00,NaN,2024,Administrative and Support and Waste Managemen...,19422,561730,0
241623,2523445,0508 Fleet and Equipment,1260044,421724313.0,BrightView,980 Jolly Road,Blue Bell,PA,19422,561730,2022,Landscaping Services,1.0,1,18,29581,2,0,0,0,0,0,0,0,0,0,0,0,0,15JAN25:18:37:00,NaN,2024,Administrative and Support and Waste Managemen...,19422,561730,0
241624,2523446,0509 Legal,1260045,421724313.0,BrightView,980 Jolly Road,Blue Bell,PA,19422,561730,2022,Landscaping Services,1.0,2,24,53654,2,0,0,0,0,0,0,0,0,0,0,0,0,15JAN25:18:37:00,NaN,2024,Administrative and Support and Waste Managemen...,19422,561730,0
241625,2523447,0510 HR Recruiting,1260046,421724313.0,BrightView,980 Jolly Road,Blue Bell,PA,19422,561730,2022,Landscaping Services,1.0,1,19,21568,2,0,0,0,0,0,0,0,0,0,0,0,0,15JAN25:18:37:00,NaN,2024,Administrative and Support and Waste Managemen...,19422,561730,0
194692,2816635,60073 SUNRISE OF JOHNS CREEK,1150310,NaN,Sunrise Senior Living LLC. SUNRISE OF JOHNS CREEK,11405 MEDLOCK BRIDGE ROAD,JOHNS CREEK,GA,30097,623312,2022,Assisted Living,1.0,21,46,87437,2,0,0,0,0,0,0,0,0,0,0,0,0,28FEB25:20:19:00,NaN,2024,Health Care and Social Assistance,30097,623312,0

# Disney looks to have the most occurrences and it is listed mutiple times so I am going to isolate it

In [170]:
# Make the establishment_name column all lowercase first
df['establishment_name'] = df['establishment_name'].str.lower()

# Filter for only Disney entries
disney = df[df["establishment_name"].str.contains('disney')]

# Save as csv to output folder
disney.to_csv("output/disney.csv", index=False)

disney

,id,establishment_name,establishment_id,ein,company_name,street_address,city,state,zip_code,naics_code,naics_year,industry_description,establishment_type,size,annual_average_employees,total_hours_worked,no_injuries_illnesses,total_deaths,total_dafw_cases,total_djtr_cases,total_other_cases,total_dafw_days,total_djtr_days,total_injuries,total_skin_disorders,total_respiratory_conditions,total_poisonings,total_hearing_loss,total_other_illnesses,created_timestamp,change_reason,year_filing_for,sector,zipcode,naics_char,All Types of Injuries
24474,2682305,"disney business productions, llc",225406,593635177.0,NaN,1375 Buena Vista Drive,Lake Buena Vista,FL,32830,713110,2012,NaN,1.0,3,266,347388,1,0,0,2,1,0,55,3,0,0,0,0,0,18FEB25:22:52:00,NaN,2024,"Arts, Entertainment, and Recreation",32830,713110,3
24480,2682314,"disney vacation development, inc.",225417,593039587.0,NaN,220 Celebration Place,Celebration,FL,34747,531390,2012,NaN,1.0,3,284,494652,1,0,2,4,1,9,297,7,0,0,0,0,0,18FEB25:22:54:00,NaN,2024,Real Estate and Rental and Leasing,34747,531390,7
24486,2682351,"disney photo imaging, llc",225432,760770488.0,NaN,1375 Buena Vista Drive,Lake Buena Vista,FL,32830,512199,2012,NaN,1.0,3,274,517835,1,0,3,5,0,35,150,8,0,0,0,0,0,18FEB25:23:11:00,NaN,2024,Information,32830,512199,8
24490,2665503,walt disney parks and resorts us inc,225446,952412883.0,NaN,1375 Buena Vista Drive,Lake Buena Vista,FL,32830,713110,2012,NaN,1.0,3,68976,104795796,1,0,797,1947,310,6952,82606,2411,9,1,0,11,622,13FEB25:20:31:00,NaN,2024,"Arts, Entertainment, and Recreation",32830,713110,3054
36140,2682882,sodexo at disney land eat ticket,340189,204855412.0,Sodexo Inc.,1313 S Harbor Blvd,Anaheim,CA,92802,722310,2012,Food Service Contractors,1.0,21,68,61679,1,0,0,0,4,0,0,3,0,0,0,0,1,19FEB25:00:45:00,Initial Submission,2024,Accommodation and Food Services,92802,722310,4
39715,2682322,"disney vacation club management, llc",371517,593039581.0,NaN,1390 Celebration Place,Celebration,FL,34747,721110,2012,NaN,1.0,3,2892,4422245,1,0,33,61,12,568,3325,85,0,0,0,1,20,18FEB25:22:58:00,NaN,2024,Accommodation and Food Services,34747,721110,106
39716,2682365,"disney financial services co., llc",371518,472350992.0,NaN,500 South Buena Vista Street,Burbank,CA,91521,541219,2012,NaN,1.0,3,823,710156,1,0,0,2,0,0,17,2,0,0,0,0,0,18FEB25:23:19:00,NaN,2024,"Professional, Scientific, and Technical Services",91521,541219,2
49428,2682369,disney global product development and creative...,467417,460478766.0,NaN,500 South Buena Vista Street,Burbank,CA,91521,713990,2012,NaN,1.0,3,414,528429,1,0,1,2,1,1,79,4,0,0,0,0,0,18FEB25:23:21:00,NaN,2024,"Arts, Entertainment, and Recreation",91521,713990,4
49429,2682377,"disney human resources services co., llc",467418,472258046.0,NaN,500 South Buena Vista Street,Burbank,CA,91521,541612,2012,NaN,1.0,3,663,52970,1,0,0,0,1,0,0,0,0,0,0,0,1,18FEB25:23:25:00,NaN,2024,"Professional, Scientific, and Technical Services",91521,541612,1
49430,2682405,"disney parks technology services co., llc",467419,811521860.0,NaN,"1375 Buena Vista Drive, 4th Floor",Lake Buena Vista,FL,32830,713110,2012,NaN,1.0,3,1659,1570221,1,0,0,3,1,0,175,3,0,0,0,0,1,18FEB25:23:31:00,NaN,2024,"Arts, Entertainment, and Recreation",32830,713110,4
49919,2696166,sodexo at disneyland neighborhood cafe,471305,204855412.0,Sodexo Inc,1313 S Harbor Blvd,Anaheim,CA,92802,722310,2012,Food Service Contractors,1.0,21,45,31136,2,0,0,0,0,0,0,0,0,0,0,0,0,19FEB25:23:44:00,NaN,2024,Accommodation and Food Services,92802,722310,0
49920,2696167,sodexo at disney land inn between,471306,204855412.0,Sodexo Inc,1313 S Harbor Blvd,Anaheim,CA,92802,722310,2012,Food Service Contractors,1.0,21,62,37764,2,0,0,0,0,0,0,0,0,0,0,0,0,19FEB25:23:44:00,NaN,2024,Accommodation and Food Services,92802,722310,0
49921,2683047,sodexo at disney land westsider grill,471307,204855412.0,Sodexo Inc.,1313 S Harbor Blvd,Anaheim,CA,92802,722310,2012,Food Service Contractors,1.0,21,25,18909,1,0,0,0,2,0,0,2,0,0,0,0,0,19FEB25:00:46:00,Initial Submission,2024,Accommodation and Food Services,92802,722310,2
49922,2696168,sodexo at disney land cafe bungalow gril,471308,204855412.0,Sodexo Inc,1313 S Harbor Blvd,Anaheim,CA,92802,722310,2012,Food Service Contractors,1.0,21,30,21048,2,0,0,0,0,0,0,0,0,0,0,0,0,19FEB25:23:44:00,NaN,2024,Accommodation and Food Services,92802,722310,0
49923,2683178,sodexo at disney land dlh cafe,471309,204855412.0,Sodexo Inc.,1313 S Harbor Blvd,Anaheim,CA,92802,722310,2012,Food Service Contractors,1.0,21,26,13203,1,0,0,0,1,0,0,1,0,0,0,0,0,19FEB25:00:47:00,Initial Submission,2024,Accommodation and Food Services,92802,722310,1
49924,2696169,sodexo at disneyland harbor point starbu,471310,204855412.0,Sodexo Inc,1313 S Harbor Blvd,Anaheim,CA,92802,722310,2012,Food Service Contractors,1.0,21,42,30145,2,0,0,0,0,0,0,0,0,0,0,0,0,19FEB25:23:44:00,NaN,2024,Accommodation and Food Services,92802,722310,0
63738,2619258,sixt rent a car - kissimmee orlando near disne...,608702,274394382.0,Sixt Rent A Car LLC,7470 W Irlo Bronson Memorial\t\t\t\t\t\t\t\t\t...,Kissimimmee,FL,34747,532111,2012,Car rental,1.0,1,5,8997,2,0,0,0,0,0,0,0,0,0,0,0,0,05FEB25:18:37:00,NaN,2024,Real Estate and Rental and Leasing,34747,532111,0
80478,2597248,walt disney imagineering - burbank/glendale,708204,950684440.0,The Walt Disney Company,500 South Buena Vista Street,Burbank,CA,91521,541715,2012,Engineering research and development laborator...,1.0,3,1080,2170986,1,0,1,3,1,2,105,4,0,0,0,0,1,31JAN25:18:40:00,NaN,2024,"Professional, Scientific, and Technical Services",91521,541715,5
80541,2772574,fl - disney nge,708645,562237457.0,GXO Logistics Supply Chain Inc,2324 Waverly Barn Road,Davenport,FL,33897,493110,2012,General Warehousing and Storage,1.0,21,27,56240,2,0,0,0,0,0,0,0,0,0,0,0,0,27FEB25:01:34:00,NaN,2024,Transportation and Warehousing,33897,493110,0
84970,2597304,the walt disney company-burbank,742158,950684440.0,The Walt Disney Company,500 South Buena Vista Street,Burbank,CA,91521,512110,2012,Motion picture and video production and distri...,1.0,3,2965,6127608,1,0,3,1,2,161,22,6,0,0,0,0,0,31JAN25:18:42:00,NaN,2024,Information,91521,512110,6
84974,2597340,the walt disney company direct to consumer,742163,950684440.0,The Walt Disney Company,500 South Buena Vista Street,Burbank,CA,91521,512110,2012,Motion picture and video production and distri...,1.0,3,1221,2508260,1,0,0,0,2,0,0,2,0,0,0,0,0,31JAN25:18:44:00,NaN,2024,Information,91521,512110,2
95107,2682330,walt disney imagineering research & developmen...,849071,954600124.0,NaN,1401 Flower Street,Glendale,CA,91221,541712,2012,Engineering research and development laborator...,1.0,3,720,893057,1,0,2,1,2,57,102,5,0,0,0,0,0,18FEB25:23:02:00,NaN,2024,"Professional, Scientific, and Technical Services",91221,541712,5
96583,2580770,the walt disney company-corporate,855324,NaN,The Walt Disney Company,147 Columbus Avenue,New York,NY,10023,512110,2012,"Program producing, television",1.0,3,406,807597,2,0,0,0,0,0,0,0,0,0,0,0,0,29JAN25:21:20:00,NaN,2024,Information,10023,512110,0
99007,2683223,sodexo at wdw team disney,863794,204855412.0,Sodexo Inc.,1375 E Buena Vista Dr,Orlando,FL,32830,722310,2012,Food Service Contractors,1.0,1,16,8339,1,0,0,0,1,0,0,1,0,0,0,0,0,19FEB25:00:47:00,Initial Submission,2024,Accommodation and Food Services,32830,722310,1
99145,2697609,sodexo at disney springs food,864200,204855412.0,Sodexo Inc,1536 E Buena Vista Drive,Lake Buena Vista,FL,32830,722310,2012,Food Service Contractors,1.0,1,6,5181,2,0,0,0,0,0,0,0,0,0,0,0,0,20FEB25:00:55:00,Initial Submission,2024,Accommodation and Food Services,32830,722310,0
122283,2597369,the walt disney company studio entertainment,954144,NaN,NaN,500 South Buena Vista Street,Burbank,CA,91521,512110,2012,"Films, motion picture production and distribution",1.0,3,2978,6467470,1,0,1,3,2,6,97,6,0,0,0,0,0,31JAN25:18:45:00,NaN,2024,Information,91521,512110,6
122284,2597400,the walt disney company/abc media networks - b...,954145,NaN,NaN,500 South Buena Vista Street,Burbank,CA,91521,512110,2012,"Program producing, television",1.0,3,1864,3832025,1,0,1,2,1,13,112,4,0,0,0,0,0,31JAN25:18:47:00,NaN,2024,Information,91521,512110,4
122286,2597459,the walt disney company fox studio,954149,NaN,NaN,10201 W. Pico Blvd.,Los Angeles,CA,90064,512110,2012,Motion picture production and distribution,1.0,3,676,1424137,2,0,0,0,0,0,0,0,0,0,0,0,0,31JAN25:18:50:00,NaN,2024,Information,90064,512110,0
122287,2597565,the walt disney company dtc wa,954150,NaN,NaN,925 4th Avenue,Seattle,WA,98104,512110,2012,"Films, motion picture production and distribution",1.0,3,602,1215695,2,0,0,0,0,0,0,0,0,0,0,0,0,31JAN25:18:56:00,NaN,2024,Information,98104,512110,0
122288,2597581,disney consumer products games publishing,954152,NaN,NaN,1200 Grand Central,Glendale,CA,91201,541430,2012,Graphic art and related design services,1.0,3,859,1749230,2,0,0,0,0,0,0,0,0,0,0,0,0,31JAN25:18:56:00,NaN,2024,"Professional, Scientific, and Technical Services",91201,541430,0
143474,2699282,sodexo at wdw team disney starbucks,1021924,204855412.0,Sodexo Inc,1375 E Buena Vista Dr,Orlando,FL,32830,561720,2012,janitorial Services,1.0,1,4,1918,2,0,0,0,0,0,0,0,0,0,0,0,0,20FEB25:01:15:00,Initial Submission,2024,Administrative and Support and Waste Managemen...,32830,561720,0
143481,2699281,sodexo at wdw team disney catering,1021983,204855412.0,Sodexo Inc,1375 E Buena Vista Dr,Orlando,FL,32830,561720,2012,janitorial Services,1.0,1,1,2008,2,0,0,0,0,0,0,0,0,0,0,0,0,20FEB25:01:15:00,Initial Submission,2024,Administrative and Support and Waste Managemen...,32830,561720,0
172783,2597595,the walt disney company-direct to consumer,1101771,NaN,NaN,525 Market Street,San Francisco,CA,94105,515210,2017,Television subscription services,1.0,3,288,594231,2,0,0,0,0,0,0,0,0,0,0,0,0,31JAN25:18:57:00,NaN,2024,Information,94105,515210,0
183407,2746151,17258 dt orlando - disney springs area,1126251,842078154.0,Hilton Worldwide Holdings Inc. DT ORLANDO - DI...,2305 HOTEL PLAZA BLVD,LAKE BUENA VISTA,FL,32830,721110,2022,Hotels,1.0,21,94,157320,1,0,2,1,1,12,34,3,0,0,0,0,1,26FEB25:01:28:00,NaN,2024,Accommodation and Food Services,32830,721110,4
183436,2746190,26588 hilton orlando lake buena vista - disney,1126295,842067873.0,Hilton Worldwide Holdings Inc. HILTON ORLANDO ...,1751 HOTEL PLAZA BLVD.,LAKE BUENA VISTA,FL,32830,721110,2022,Hotels,1.0,3,312,491898,1,0,6,5,5,367,401,11,0,0,0,0,5,26FEB25:01:28:00,NaN,2024,Accommodation and Food Services,32830,721110,16
183468,2746277,49019 hilton orl buena vista pal disney spgs,1126383,842067873.0,Hilton Worldwide Holdings Inc. HILTON ORL BUEN...,1900 EAST BUENA VISTA DRIVE,LAKE BUENA VISTA,FL,32830,721110,2022,Hotels,1.0,3,401,584873,1,0,3,3,3,36,299,8,0,0,0,0,1,26FEB25:01:29:00,NaN,2024,Accommodation and Food Services,32830,721110,9
183764,2860458,holiday inn disney springs,1127013,522101817.0,Aimbridge,1805 Hotel Plaza Blvd,Lake Buena Vista,FL,32830,721110,2022,Hotels (except casino hotels),1.0,21,75,153953,1,0,1,0,0,2,23,1,0,0,0,0,0,05MAR25:15:33:00,NaN,2024,Accommodation and Food Services,32830,721110,1
258298,2580379,the walt disney company - abc,1278196,NaN,NaN,77 West 66th Street,New York,NY,10023,516120,2022,Television broadcasting stations,1.0,3,1523,3143405,1,0,0,1,1,0,30,2,0,0,0,0,0,29JAN25:20:49:00,NaN,2024,Information,10023,516120,2
258429,2580863,the walt disney company - 1500 broadway,1278350,NaN,NaN,1500 Broadway,New York,NY,10036,516120,2022,Television broadcasting stations,1.0,1,12,23052,1,0,1,0,1,2,0,2,0,0,0,0,0,29JAN25:21:23:00,NaN,2024,Information,10036,516120,2
260367,2586672,the walt disney company - corporate,1280484,NaN,NaN,214 W 42nd Street,New York,NY,10036,516120,2022,Television broadcasting stations,1.0,3,749,366441,2,0,0,0,0,0,0,0,0,0,0,0,0,30JAN25:18:35:00,NaN,2024,Information,10036,516120,0
276569,2634788,1632 - walt disney wor,1297765,230334400.0,Ricoh USA Inc,1000 W BUENA VISTA DR,LAKE BUENA VISTA,FL,32830,423420,2022,Office Equipment,1.0,1,14,28000,2,0,0,0,0,0,0,0,0,0,0,0,0,10FEB25:15:47:00,NaN,2024,Wholesale Trade,32830,423420,0
288654,2669742,caravan fm -disney phase 1,1310362,383376680.0,Caravan Facilities Management LLC,Walt Disney World,Orlando,FL,32830,561720,2022,Janitorial services,1.0,22,104,184466,1,0,1,0,0,3,0,1,0,0,0,0,0,14FEB25:20:53:00,NaN,2024,Administrative and Support and Waste Managemen...,32830,561720,1
288662,2669774,caravan fm -disney textiles,1310371,383376680.0,Caravan Facilities Management LLC,3451 Bonnet Creek Road,Lake Buena Vista,FL,38230,561720,2022,Janitorial services,1.0,21,26,52858,1,0,2,0,0,48,0,2,0,0,0,0,0,14FEB25:20:56:00,NaN,2024,Administrative and Support and Waste Managemen...,38230,561720,2
291755,2679236,"walt disney parks and resorts u.s. inc., dba d...",1313632,952412883.0,The Walt Disney Company,1313 S. Harbor Blvd,Anaheim,CA,92802,713110,2022,"Amusement parks (e.g., theme, water)",1.0,3,40525,53684779,1,1,999,1116,250,47502,88529,1952,1,0,0,2,411,25FEB25:19:14:00,NaN,2024,"Arts, Entertainment, and Recreation",92802,713110,2366
297451,2697607,sodexo at disney parks and resorts,1319773,204855412.0,Sodexo Inc,1375 E Buena Vista Dr,Orlando,FL,32830,722310,2022,Food Service Contractors,1.0,1,11,11236,2,0,0,0,0,0,0,0,0,0,0,0,0,20FEB25:00:55:00,Initial Submission,2024,Accommodation and Food Services,32830,722310,0
301188,2706421,disney appear care,1323609,204855412.0,Sodexo Inc,1536 E Buena Vista Dr 2Nc Floor Cas,Lake Buena Vista,FL,32830,561720,2022,Building Cleaning Maintenance,1.0,21,61,122000,2,0,0,0,0,0,0,0,0,0,0,0,0,20FEB25:20:49:00,Initial Submission,2024,Administrative and Support and Waste Managemen...,32830,561720,0
301523,2706790,disneyland resort marketing,1323944,204855412.0,Sodexo Inc,911 S Rifle St,Aurora,CO,80017,722310,2022,Food Service Contractors,1.0,1,1,2000,2,0,0,0,0,0,0,0,0,0,0,0,0,20FEB25:20:51:00,Initial Submission,2024,Accommodation and Food Services,80017,722310,0
304113,2713812,disney vacation club hawaii management company...,1326570,272432600.0,The Walt Disney Company,92-1185 Aliinui Drive,Kapolei,HI,96707,721110,2022,"Hotels, resort, without casinos",1.0,3,1670,2536015,1,0,59,1,12,2494,1114,71,1,0,0,0,0,25FEB25:19:12:00,NaN,2024,Accommodation and Food Services,96707,721110,72
304275,2714183,"walt disney travel co., llc",1326735,952553603.0,The Walt Disney Company,"190 Center Street Promenade, Suite 1955",Anaheim,CA,92805,561510,2022,Travel agencies,1.0,3,535,757019,1,0,0,0,1,0,0,0,0,0,0,0,1,26FEB25:23:01:00,NaN,2024,Administrative and Support and Waste Managemen...,92805,561510,1
304977,2716147,t.disney trucking and grading inc,1327468,200729606.0,T.Disney Trucking and Grading Inc,6324 US HWY 301 S,Riverview,FL,33578,484220,2022,"Dump trucking (e.g., gravel, sand, top soil)",1.0,21,31,64480,2,0,0,0,0,0,0,0,0,0,0,0,0,21FEB25:19:55:00,NaN,2024,Transportation and Warehousing,33578,484220,0
356476,2823238,26-016 disney concert hall region 1,1380095,202264403.0,PCAM LLC,111 SOUTH GRAND AVENUE,LOS ANGELES,CA,90012,812930,2022,PARKING LOTS AND GARAGES,1.0,21,897,1565272,1,0,0,1,0,0,2,1,0,0,0,0,0,28FEB25:22:25:00,NaN,2024,Other Services,90012,812930,1
356764,2823850,disneyland anaheim,1380393,10572964.0,VENUPLUS INC,1313 Disneyland Dr,Anaheim,CA,92802,532490,2022,532490 Other Commercial and Industrial Machine...,1.0,1,7,12601,2,0,0,0,0,0,0,0,0,0,0,0,0,28FEB25:22:35:00,NaN,2024,Real Estate and Rental and Leasing,92802,532490,0
356765,2823851,disneys magic kingdom,1380394,10572964.0,VENUPLUS INC,1180 Seven Seas Drive,Lake Buena Vista,FL,32830,532490,2022,532490 Other Commercial and Industrial Machine...,1.0,1,3,5604,2,0,0,0,0,0,0,0,0,0,0,0,0,28FEB25:22:35:00,NaN,2024,Real Estate and Rental and Leasing,32830,532490,0
356766,2823852,disneys typhoon lagoon,1380395,10572964.0,VENUPLUS INC,1145 E Buena Vista Dr,Orlando,FL,32821,532490,2022,532490 Other Commercial and Industrial Machine...,1.0,1,4,8391,2,0,0,0,0,0,0,0,0,0,0,0,0,28FEB25:22:35:00,NaN,2024,Real Estate and Rental and Leasing,32821,532490,0
356831,2823918,disneys epcot,1380460,10572964.0,VENUPLUS INC,200 Epcot Center Drive,Orlando,FL,32830,532490,2022,532490 Other Commercial and Industrial Machine...,1.0,1,2,3876,2,0,0,0,0,0,0,0,0,0,0,0,0,28FEB25:22:35:00,NaN,2024,Real Estate and Rental and Leasing,32830,532490,0
356832,2823919,disneys hollywood studios,1380461,10572964.0,VENUPLUS INC,351 S Studio Drive,Lake Buena Vista,FL,32830,532490,2022,532490 Other Commercial and Industrial Machine...,1.0,1,1,259,2,0,0,0,0,0,0,0,0,0,0,0,0,28FEB25:22:35:00,NaN,2024,Real Estate and Rental and Leasing,32830,532490,0
356833,2823920,disneys animal kingdom,1380462,10572964.0,VENUPLUS INC,2901 Osceola Pkwy,Lake Buena Vista,FL,32830,713120,2022,713120 Amusement Arcades,1.0,1,1,28,2,0,0,0,0,0,0,0,0,0,0,0,0,28FEB25:22:35:00,NaN,2024,"Arts, Entertainment, and Recreation",32830,713120,0
358578,2828495,cbre - disney,1382267,952743174.0,CBRE Inc,627 Hazel St,Glendale,CA,91201,561210,2022,Activities related to Real Estate and Faciliti...,1.0,21,49,102074,2,0,0,0,0,0,0,0,0,0,0,0,0,01MAR25:03:15:00,NaN,2024,Administrative and Support and Waste Managemen...,91201,561210,0

# How many injuries across all Disney locations were there in 2024?

In [138]:
disney["All Types of Injuries"].sum()

5702

# How many average employees are there across all the locations in 2024?

In [141]:
disney["annual_average_employees"].sum()

137375

# Rate of injury across Disney locations based on average employees

In [143]:
disney_injury_rate = disney["All Types of Injuries"].sum() / disney["annual_average_employees"].sum()
disney_injury_rate

0.041506824385805274

# The high number of injuries is notable but the rate of injury is low as Disney employs many people. Curious to see rates across the dataset

In [150]:
# Measuring just total injuries
df["Injuries per Average Employee"] = df["total_injuries"] / df["annual_average_employees"]
df.sort_values(by="Injuries per Average Employee", ascending=False).head(10)

,id,establishment_name,establishment_id,ein,company_name,street_address,city,state,zip_code,naics_code,naics_year,industry_description,establishment_type,size,annual_average_employees,total_hours_worked,no_injuries_illnesses,total_deaths,total_dafw_cases,total_djtr_cases,total_other_cases,total_dafw_days,total_djtr_days,total_injuries,total_skin_disorders,total_respiratory_conditions,total_poisonings,total_hearing_loss,total_other_illnesses,created_timestamp,change_reason,year_filing_for,sector,zipcode,naics_char,All Types of Injuries,Injuries per Average Employee
300190,2704716,integrated tower systems,1322594,NaN,NaN,2703 Dawson Road,Tulsa,OK,74110,332312,2022,"Structural steel, fabricated, manufacturing",1.0,1,10,18300,1,0,0,147,0,0,2,147,0,0,0,0,0,20FEB25:18:48:00,NaN,2024,Manufacturing,74110,332312,147,14.700
135034,2513551,cencal delivery llc,995055,845092345.0,CenCal Delivery LLC,21885 Eastmere Lane,Friant,CA,93626,492110,2012,Couriers and Express Delivery Services,1.0,1,1,0,1,0,1,2,9,15,36,12,0,0,0,0,0,11JAN25:00:07:00,NaN,2024,Transportation and Warehousing,93626,492110,12,12.000
238214,2509785,"hodo, inc.",1256346,204682352.0,"Hodo, Inc.",2923 Adeline St.,Oakland,CA,94608,311991,2022,NaN,1.0,22,1,322400,1,0,9,1,0,119,57,10,0,0,0,0,0,09JAN25:18:30:00,NaN,2024,Manufacturing,94608,311991,10,10.000
106905,2499461,systems plus lumber co. inc.,904908,941732007.0,Haisch Construction Company Inc.,1800 S. Barney Rd.,Anderson,CA,96007,321214,2012,"Floor trusses, wood, manufacturing",1.0,21,1,41926,1,0,1,0,7,5,0,8,0,0,0,0,0,02JAN25:23:19:00,NaN,2024,Manufacturing,96007,321214,8,8.000
70393,2517896,"fuse fabrication, llc",649342,274116195.0,"Fuse Fabrication, LLC",1935 Industrial Park Rd,Mulberry,FL,33860,238190,2012,"Welding, on site, contractors",1.0,21,1,1480,1,0,3,0,4,6,0,7,0,0,0,0,0,01APR25:18:29:00,NaN,2024,Construction,33860,238190,7,7.000
352010,2819335,nyc health hospitals gouverneur skilled nursing,1375515,132655001.0,NYC Health Hospitals,227 Madison Street,New York,NY,10002,623110,2022,Nursing Facility,3.0,1,2,1860,1,0,14,0,0,1487,0,14,0,0,0,0,0,28FEB25:21:01:00,NaN,2024,Health Care and Social Assistance,10002,623110,14,7.000
290487,2675094,geisinger behavioral health centernortheast,1312254,861906198.0,Acadia Healthcare Management Company Inc,60 Glenmaura National Blvd,Moosic,PA,18507,622210,2022,Outpatient mental health and substance abuse c...,1.0,1,3,5848,1,0,3,7,11,144,254,21,0,0,0,0,0,17FEB25:20:44:00,NaN,2024,Health Care and Social Assistance,18507,622210,21,7.000
19255,2805533,mason store,185080,381426892.0,Goodwill Industries of Central Michigans Heart...,652 Hull Road,Mason,MI,48854,459510,2012,Thrift Shop,1.0,1,16,30780,1,0,0,106,0,0,7,106,0,0,0,0,0,28FEB25:15:37:00,NaN,2024,Retail Trade,48854,459510,106,6.625
132672,2664777,juzt construction inc.,987220,860768065.0,Juzt Construction Inc.,3861 East Via Del Rancho Road,Gilbert,AZ,85298,238130,2012,"Carpentry, framing",1.0,21,1,36518,1,0,1,1,4,21,7,6,0,0,0,0,0,13FEB25:19:05:00,NaN,2024,Construction,85298,238130,6,6.000
210984,2500665,ilum solar -bakersfield,1181182,474972757.0,Ilum Solar,"3748 Renfro Rd, Unit B",Bakerfield,CA,93314,238210,2022,Electrical contractors,1.0,21,1,74490,1,0,1,0,5,14,0,6,0,0,0,0,0,03JAN25:20:12:00,NaN,2024,Construction,93314,238210,6,6.000

In [102]:
# Measuring all types of injuries rate
df["All Types of Injuries per Average Employee"] = df["All Types of Injuries"] / df["annual_average_employees"]
df.sort_values(by="All Types of Injuries per Average Employee", ascending=False).head(15)

,id,establishment_name,establishment_id,ein,company_name,street_address,city,state,zip_code,naics_code,naics_year,industry_description,establishment_type,size,annual_average_employees,total_hours_worked,no_injuries_illnesses,total_deaths,total_dafw_cases,total_djtr_cases,total_other_cases,total_dafw_days,total_djtr_days,total_injuries,total_skin_disorders,total_respiratory_conditions,total_poisonings,total_hearing_loss,total_other_illnesses,created_timestamp,change_reason,year_filing_for,sector,zipcode,naics_char,Injuries per Average Employee,All Types of Injuries,All Types of Injuries per Average Employee
300190,2704716,integrated tower systems,1322594,NaN,NaN,2703 Dawson Road,Tulsa,OK,74110,332312,2022,"Structural steel, fabricated, manufacturing",1.0,1,10,18300,1,0,0,147,0,0,2,147,0,0,0,0,0,20FEB25:18:48:00,NaN,2024,Manufacturing,74110,332312,14.700,147,14.700
135034,2513551,cencal delivery llc,995055,845092345.0,CenCal Delivery LLC,21885 Eastmere Lane,Friant,CA,93626,492110,2012,Couriers and Express Delivery Services,1.0,1,1,0,1,0,1,2,9,15,36,12,0,0,0,0,0,11JAN25:00:07:00,NaN,2024,Transportation and Warehousing,93626,492110,12.000,12,12.000
238214,2509785,"hodo, inc.",1256346,204682352.0,"Hodo, Inc.",2923 Adeline St.,Oakland,CA,94608,311991,2022,NaN,1.0,22,1,322400,1,0,9,1,0,119,57,10,0,0,0,0,0,09JAN25:18:30:00,NaN,2024,Manufacturing,94608,311991,10.000,10,10.000
106905,2499461,systems plus lumber co. inc.,904908,941732007.0,Haisch Construction Company Inc.,1800 S. Barney Rd.,Anderson,CA,96007,321214,2012,"Floor trusses, wood, manufacturing",1.0,21,1,41926,1,0,1,0,7,5,0,8,0,0,0,0,0,02JAN25:23:19:00,NaN,2024,Manufacturing,96007,321214,8.000,8,8.000
352010,2819335,nyc health hospitals gouverneur skilled nursing,1375515,132655001.0,NYC Health Hospitals,227 Madison Street,New York,NY,10002,623110,2022,Nursing Facility,3.0,1,2,1860,1,0,14,0,0,1487,0,14,0,0,0,0,0,28FEB25:21:01:00,NaN,2024,Health Care and Social Assistance,10002,623110,7.000,14,7.000
70393,2517896,"fuse fabrication, llc",649342,274116195.0,"Fuse Fabrication, LLC",1935 Industrial Park Rd,Mulberry,FL,33860,238190,2012,"Welding, on site, contractors",1.0,21,1,1480,1,0,3,0,4,6,0,7,0,0,0,0,0,01APR25:18:29:00,NaN,2024,Construction,33860,238190,7.000,7,7.000
231842,2755985,cleveland operations,1245735,452262555.0,Prolink Staffing Services LLC,3 Summit Park Dr. Suite 325,Independence,OH,44131,561311,2022,NaN,1.0,1,1,5,1,0,2,0,5,65,0,4,0,0,0,0,3,26FEB25:17:55:00,NaN,2024,Administrative and Support and Waste Managemen...,44131,561311,4.000,7,7.000
290487,2675094,geisinger behavioral health centernortheast,1312254,861906198.0,Acadia Healthcare Management Company Inc,60 Glenmaura National Blvd,Moosic,PA,18507,622210,2022,Outpatient mental health and substance abuse c...,1.0,1,3,5848,1,0,3,7,11,144,254,21,0,0,0,0,0,17FEB25:20:44:00,NaN,2024,Health Care and Social Assistance,18507,622210,7.000,21,7.000
19255,2805533,mason store,185080,381426892.0,Goodwill Industries of Central Michigans Heart...,652 Hull Road,Mason,MI,48854,459510,2012,Thrift Shop,1.0,1,16,30780,1,0,0,106,0,0,7,106,0,0,0,0,0,28FEB25:15:37:00,NaN,2024,Retail Trade,48854,459510,6.625,106,6.625
132672,2664777,juzt construction inc.,987220,860768065.0,Juzt Construction Inc.,3861 East Via Del Rancho Road,Gilbert,AZ,85298,238130,2012,"Carpentry, framing",1.0,21,1,36518,1,0,1,1,4,21,7,6,0,0,0,0,0,13FEB25:19:05:00,NaN,2024,Construction,85298,238130,6.000,6,6.000
210984,2500665,ilum solar -bakersfield,1181182,474972757.0,Ilum Solar,"3748 Renfro Rd, Unit B",Bakerfield,CA,93314,238210,2022,Electrical contractors,1.0,21,1,74490,1,0,1,0,5,14,0,6,0,0,0,0,0,03JAN25:20:12:00,NaN,2024,Construction,93314,238210,6.000,6,6.000
389817,2886803,ana's place,1414973,NaN,DHS,4380 Bronx Blvd,Bronx,NY,10466,923130,2022,Community social service program administration,3.0,1,1,31144,1,0,5,0,1,194,0,3,0,0,0,0,3,23APR25:15:25:00,NaN,2024,Public Administration,10466,923130,3.000,6,6.000
200917,2647985,gravois_1365462,1161436,417600000.0,US Postal Service,4455 RIDGEWOOD AVE,SAINT LOUIS,MO,63116,491110,2022,Mail and Parcel Delivery,2.0,1,2,1840,1,0,1,9,1,13,247,11,0,0,0,0,0,10FEB25:23:11:00,NaN,2024,Transportation and Warehousing,63116,491110,5.500,11,5.500
200678,2648099,downtown northbrook_1375495,1161192,417600000.0,US Postal Service,1157 CHURCH ST,NORTHBROOK,IL,60062,491110,2022,Mail and Parcel Delivery,2.0,1,1,284,1,0,3,1,1,39,35,5,0,0,0,0,0,10FEB25:23:19:00,NaN,2024,Transportation and Warehousing,60062,491110,5.000,5,5.000
201727,2648059,berlin_1354745,1162283,417600000.0,US Postal Service,20 BROAD ST,BERLIN,MD,21811,491110,2022,Mail and Parcel Delivery,2.0,1,1,2747,1,0,3,0,2,63,24,5,0,0,0,0,0,10FEB25:23:16:00,NaN,2024,Transportation and Warehousing,21811,491110,5.000,5,5.000

In [161]:
all_inj_sector_summ = df.groupby('sector')[['All Types of Injuries', 'annual_average_employees']].sum().reset_index()
all_inj_sector_summ["Injury Rate"] = all_inj_sector_summ['All Types of Injuries'] / all_inj_sector_summ['annual_average_employees']
all_inj_sector_summ.to_csv("output/all_inj_sector_summ.csv", index=False)
all_inj_sector_summ.sort_values(by='Injury Rate', ascending=False)

,sector,All Types of Injuries,annual_average_employees,Injury Rate
14,Public Administration,57740,1229633,0.046957
17,Transportation and Warehousing,248872,5891436,0.042243
3,"Arts, Entertainment, and Recreation",25522,838601,0.030434
16,Retail Trade,212463,7447655,0.028528
18,Unknown,114,4236,0.026912
20,Wholesale Trade,68359,2554670,0.026758
12,Other Services,12843,545491,0.023544
15,Real Estate and Rental and Leasing,11467,533270,0.021503
0,Accommodation and Food Services,44725,2125817,0.021039
19,Utilities,11773,569962,0.020656
1,Administrative and Support and Waste Managemen...,39027,2007223,0.019443
5,Educational Services,20789,1078139,0.019282
2,"Agriculture, Forestry, Fishing and Hunting",19322,1203438,0.016056
10,Manufacturing,250161,15700826,0.015933
11,"Mining, Quarrying, and Oil and Gas Extraction",1180,130198,0.009063
13,"Professional, Scientific, and Technical Services",6540,735341,0.008894
8,Information,5478,634945,0.008628
9,Management of Companies and Enterprises,1924,390540,0.004927
7,Health Care and Social Assistance,360831,75277919,0.004793
4,Construction,71464,18002877,0.003970
6,Finance and Insurance,908,726621,0.001250

In [168]:
all_death_sector_summ = df.groupby('sector')[['total_deaths', 'annual_average_employees']].sum().reset_index()
all_death_sector_summ["Death Rate"] = all_death_sector_summ['total_deaths'] / all_death_sector_summ['annual_average_employees']
all_death_sector_summ.to_csv("output/all_death_sector_summ.csv", index=False)
all_death_sector_summ.sort_values(by='Death Rate', ascending=False)

,sector,total_deaths,annual_average_employees,Death Rate
14,Public Administration,65,1229633,5.286130e-05
11,"Mining, Quarrying, and Oil and Gas Extraction",5,130198,3.840305e-05
19,Utilities,18,569962,3.158105e-05
17,Transportation and Warehousing,159,5891436,2.698833e-05
1,Administrative and Support and Waste Managemen...,53,2007223,2.640464e-05
2,"Agriculture, Forestry, Fishing and Hunting",29,1203438,2.409763e-05
15,Real Estate and Rental and Leasing,8,533270,1.500178e-05
20,Wholesale Trade,35,2554670,1.370040e-05
12,Other Services,7,545491,1.283248e-05
3,"Arts, Entertainment, and Recreation",9,838601,1.073216e-05
10,Manufacturing,138,15700826,8.789346e-06
4,Construction,156,18002877,8.665282e-06
8,Information,5,634945,7.874698e-06
9,Management of Companies and Enterprises,2,390540,5.121114e-06
16,Retail Trade,37,7447655,4.968007e-06
0,Accommodation and Food Services,10,2125817,4.704074e-06
5,Educational Services,5,1078139,4.637621e-06
13,"Professional, Scientific, and Technical Services",3,735341,4.079740e-06
7,Health Care and Social Assistance,34,75277919,4.516597e-07
6,Finance and Insurance,0,726621,0.000000e+00
18,Unknown,0,4236,0.000000e+00